kind: Deployment
apiVersion: apps/v1
metadata:
  name: glauth
  labels:
    app: glauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glauth
  template:
    labels:
      app: glauth
    spec:
      volumes:
        - name: config
          configMap:
            name: glauth-config
      containers:
        - resources: {}
          name: glauth
          env:
            - name: GLAUTH_CONFIG
              value: /app/config/config.cfg
          ports:
            - containerPort: 389
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /app/config
          terminationMessagePolicy: File
          image: 'docker.io/glauth/glauth:v2.3.2'
